/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: adf9030d42573bf75f7f233a6bb37d44)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
		GOOGLE_SERVICE_ACCOUNT_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_SERVICE_ACCOUNT_KEY">> {}
}
